const Meta = Object.freeze({
  wordtopdf: {
    icon: "/icons/word-to-pdf.svg",
    src: "Word",
    tgt: "PDF",
    srcType: ["doc", "docx"],
    tgtType: "pdf",
    wrongInput: "Please Provide a doc or docx file",
    conversion: "docxtopdf",
    srcIcon: "/icons/word.svg",
    tgtIcon: "/icons/pdf.svg",
  },
  exceltopdf: {
    icon: "/icons/excel-to-pdf.svg",
    src: "Excel",
    tgt: "PDF",
    srcType: ["xls", "xlsx"],
    tgtType: "pdf",
    wrongInput: "Please Provide a xls or xlsx file",
    conversion: "xlsxtopdf",
    srcIcon: "/icons/excel.svg",
    tgtIcon: "/icons/pdf.svg",
  },
  ppttopdf: {
    icon: "/icons/ppt-to-pdf.svg",
    src: "Power Point",
    tgt: "PDF",
    srcType: ["ppt", "pptx"],
    tgtType: "pdf",
    wrongInput: "Please Provide a ppt or pptx file",
    conversion: "pptxtopdf",
    srcIcon: "/icons/ppt.svg",
    tgtIcon: "/icons/pdf.svg",
  },
  ebookstopdf: {
    icon: "/icons/ebooks-to-pdf.svg",
    src: "eBooks",
    tgt: "PDF",
    srcType: ["epub"],
    tgtType: "pdf",
    wrongInput: "Please provide an epub file",
    conversion: "epubtopdf",
    srcIcon: "/icons/ebooks.svg",
    tgtIcon: "/icons/pdf.svg",
  },
  iworktopdf: {
    icon: "/icons/iwork-to-pdf.svg",
    src: "iWork",
    tgt: "PDF",
    srcType: ["epub"],
    tgtType: "pdf",
    wrongInput: "please provide an iwork file",
    conversion: "epubtopdf",
    srcIcon: "/icons/iwork.svg",
    tgtIcon: "/icons/pdf.svg",
  },
  pdftoword: {
    icon: "/icons/pdf-to-word.svg",
    src: "PDF",
    tgt: "Word",
    srcType: ["pdf"],
    tgtType: "docx",
    wrongInput: "Please provide a pdf file",
    conversion: "pdftodocx",
    srcIcon: "/icons/pdf.svg",
    tgtIcon: "/icons/word.svg",
  },
  pdftoexcel: {
    icon: "/icons/pdf-to-excel.svg",
    src: "PDF",
    tgt: "Excel",
    srcType: ["pdf"],
    tgtType: "xlsx",
    wrongInput: "Please provide a pdf file",
    conversion: "pdftoxlsx",
    srcIcon: "/icons/pdf.svg",
    tgtIcon: "/icons/excel.svg",
  },
  pdftoppt: {
    icon: "/icons/pdf-to-ppt.svg",
    src: "PDF",
    tgt: "Power Point",
    srcType: ["pdf"],
    tgtType: "pptx",
    wrongInput: "Please provide a pdf file",
    conversion: "pdftopptx",
    srcIcon: "/icons/pdf.svg",
    tgtIcon: "/icons/ppt.svg",
  },
  pdftojpg: {
    icon: "/icons/pdf-to-img.svg",
    src: "PDF",
    tgt: "JPG",
    srcType: ["pdf"],
    tgtType: "jpg",
    wrongInput: "Please provide a pdf file",
    conversion: "pdftoimg",
    srcIcon: "/icons/pdf.svg",
    tgtIcon: "/icons/image.svg",
  },
  pdftopng: {
    icon: "/icons/pdf-to-img.svg",
    src: "PDF",
    tgt: "PNG",
    srcType: ["pdf"],
    tgtType: "png",
    wrongInput: "Please provide a pdf file",
    conversion: "pdftoimg",
    srcIcon: "/icons/pdf.svg",
    tgtIcon: "/icons/image.svg",
  },
  jpgtopdf: {
    icon: "/icons/img-to-pdf.svg",
    src: "JPG",
    tgt: "PDF",
    srcType: ["jpg"],
    tgtType: "pdf",
    wrongInput: "Please Provide a jpg file",
    conversion: "imgtopdf",
    srcIcon: "/icons/image.svg",
    tgtIcon: "/icons/pdf.svg",
  },
  pngtopdf: {
    icon: "/icons/img-to-pdf.svg",
    src: "PNG",
    tgt: "PDF",
    srcType: ["png"],
    tgtType: "pdf",
    wrongInput: "Please Provide a png file",
    conversion: "imgtopdf",
    srcIcon: "/icons/image.svg",
    tgtIcon: "/icons/pdf.svg",
  },
});

export default Meta;
